#!/usr/bin/env bash

set -eux

uv publish --username=__token__ --password=pypi-AgEIcHlwaS5vcmcCJDBmYTQ1MDg1LTgyNjctNGExNi05ZTViLTFmMDc3NjY1YjFkZQACDlsxLFsid3VqaW5nIl1dAAIsWzIsWyI0NGUwY2QxNC00ODM0LTQzN2MtYTkyNi1kZjNjYTk3OGEyNzUiXV0AAAYgAGh4lIJ-3Ca6nPV_OsxzAZpqi_Qj2sc6FBKR7l7ypUo