class VStoreError(Exception): ...
class InvalidConfiguration(VStoreError): ...
class BackendClosed(VStoreError): ...
class DimensionMismatch(VStoreError): ...
class QueryError(VStoreError): ...
class InsertionError(VStoreError): ...
