list_cols_df_verification = [
    "period",
    "ou_id",
    "level_2_uid",
    "level_2_name",
    "level_3_uid",
    "level_3_name",
    "level_4_uid",
    "level_4_name",
    "level_5_uid",
    "level_5_name",
    "level_6_uid",
    "level_6_name",
    "bool_verified",
    "diff_in_subsidies_decval_period",
    "diff_in_subsidies_tauxval_period",
    "benefice_complet_vbr",
    "taux_validation",
    "subside_dec_period",
    "subside_val_period",
    "subside_taux_period",
    "ecart_median_per_services",
    "ecart_median_general",
    "ecart_average_general",
    "categorie_risque",
    "high_risk_quality_indicators",
    "middle_risk_quality_indicators",
    "low_risk_quality_indicators",
    "nb_services_above_seuil",
    "nb_services",
]

list_cols_df_stats = [
    "province",
    "periode",
    "total number of centres",
    "number of centers high risk",
    "number of centers middle risk",
    "number of centers low risk",
    "number of verified centers",
    "cost of verification (VBR)",
    "cost of verification (syst)",
    "subsidies (VBR)",
    "subsidies (syst)",
    "total cost (VBR)",
    "total cost (syst)",
    "ratio cost_verification cost_total (VBR)",
    "ratio cost_verification cost_total (syst)",
    "Number of centers where vbr was beneficial",
    "Number of centers over-subsidized",
    "Money saved by VBR (taking into account verif costs)",
    "Amount of over-subsidies",
    "Average of over-subsidies (non-verified centers)",
    "Average of over-subsidies (verified centers)",
    "Average number of high risk quality indicators (non-verified centers)",
    "Average number of high risk quality indicators (verified centers)",
    "Average number of middle risk quality indicators (non-verified centers)",
    "Average number of middle risk quality indicators (verified centers)",
    "Average number of low risk quality indicators (non-verified centers)",
    "Average number of low risk quality indicators (verified centers)",
]
list_cols_df_services = [
    "period",
    "ou_id",
    "Category of the center",
    "bool verified",
    "Risk category",
    "service",
    "Taux of validation",
    "Ecart median",
]
