class StockType:
    TATASTEEL: str
    ONGC: str
    POWERGRID: str
    NTPC: str
    ITC: str
    COALINDIA: str
    UPL: str
    WIPRO: str
    HINDALCO: str
    HDFCLIFE: str
    BPCL: str
    SBIN: str
    JSWSTEEL: str
    TATAMOTORS: str
    ICICIBANK: str
    AXISBANK: str
    BHARTIARTL: str
    TATACONSUM: str
    TECHM: str
    ADANIPORTS: str
    HDFCBANK: str
    CIPLA: str
    SBILIFE: str
    BAJAJFINSV: str
    INDUSINDBK: str
    INFY: str
    SUNPHARMA: str
    HCLTECH: str
    KOTAKBANK: str
    M_M: str
    GRASIM: str
    HINDUNILVR: str
    NESTLEIND: str
    ASIANPAINT: str
    RELIANCE: str
    ADANIENT: str
    DIVISLAB: str
    LT: str
    TITAN: str
    EICHERMOT: str
    TCS: str
    HEROMOTOCO: str
    BRITANNIA: str
    LTIM: str
    APOLLOHOSP: str
    DRREDDY: str
    BAJFINANCE: str
    BAJAJ_AUTO: str
    ULTRACEMCO: str
    MARUTI: str
