
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-11T18:51:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "64c3e25528ca51bbfefea94955215179854a25b4",
 "version": "2.67.3b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
