
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-11T14:01:37+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b36dacb4355d622dfaee2e0592f4c7c93f88f01f",
 "version": "2.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
