# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_package.proto

import sys
_b = sys.version_info[0] < 3 and (lambda x: x) or (
    lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='model_package.proto',
    package='MODEL_PACKAGE',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x13model_package.proto\x12\rMODEL_PACKAGE\"\xc3\x01\n\x11ModelPackageProto\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x11\n\tmodel_num\x18\x02 \x01(\x03\x12\x13\n\x0bmodel_names\x18\x03 \x03(\t\x12\x43\n\nmodel_data\x18\x04 \x03(\x0b\x32/.MODEL_PACKAGE.ModelPackageProto.ModelDataEntry\x1a\x30\n\x0eModelDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x62\x06proto3'
    ))

_MODELPACKAGEPROTO_MODELDATAENTRY = _descriptor.Descriptor(
    name='ModelDataEntry',
    full_name='MODEL_PACKAGE.ModelPackageProto.ModelDataEntry',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='key',
            full_name='MODEL_PACKAGE.ModelPackageProto.ModelDataEntry.key',
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode('utf-8'),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='value',
            full_name='MODEL_PACKAGE.ModelPackageProto.ModelDataEntry.value',
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=_b('8\001'),
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=186,
    serialized_end=234,
)

_MODELPACKAGEPROTO = _descriptor.Descriptor(
    name='ModelPackageProto',
    full_name='MODEL_PACKAGE.ModelPackageProto',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='version',
            full_name='MODEL_PACKAGE.ModelPackageProto.version',
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='model_num',
            full_name='MODEL_PACKAGE.ModelPackageProto.model_num',
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='model_names',
            full_name='MODEL_PACKAGE.ModelPackageProto.model_names',
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='model_data',
            full_name='MODEL_PACKAGE.ModelPackageProto.model_data',
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[
        _MODELPACKAGEPROTO_MODELDATAENTRY,
    ],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=39,
    serialized_end=234,
)

_MODELPACKAGEPROTO_MODELDATAENTRY.containing_type = _MODELPACKAGEPROTO
_MODELPACKAGEPROTO.fields_by_name[
    'model_data'].message_type = _MODELPACKAGEPROTO_MODELDATAENTRY
DESCRIPTOR.message_types_by_name['ModelPackageProto'] = _MODELPACKAGEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ModelPackageProto = _reflection.GeneratedProtocolMessageType(
    'ModelPackageProto',
    (_message.Message, ),
    {
        'ModelDataEntry':
            _reflection.GeneratedProtocolMessageType(
                'ModelDataEntry',
                (_message.Message, ),
                {
                    'DESCRIPTOR': _MODELPACKAGEPROTO_MODELDATAENTRY,
                    '__module__': 'model_package_pb2'
                    # @@protoc_insertion_point(class_scope:MODEL_PACKAGE.ModelPackageProto.ModelDataEntry)
                }),
        'DESCRIPTOR':
            _MODELPACKAGEPROTO,
        '__module__':
            'model_package_pb2'
        # @@protoc_insertion_point(class_scope:MODEL_PACKAGE.ModelPackageProto)
    })
_sym_db.RegisterMessage(ModelPackageProto)
_sym_db.RegisterMessage(ModelPackageProto.ModelDataEntry)

_MODELPACKAGEPROTO_MODELDATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
