#!/usr/bin/python3
# @Time    : 2024-05-16
# @Author  : Kevin Kong (kfx2007@163.com)

from alipay.comm import AntomCore


class Authorization(AntomCore):
    def consult(
        self,
        customerBelongsTo,
        authRedirectUrl,
        scopes,
        authState,
        terminalType="WEB",
        osType=None,
        osVersion=None,
        merchantRegion=None,
        authClientId=None,
    ):
        """
        get user authorization.

        Params:
        :param customerBelongsTo: Payment Method.
        :param authRedirectUrl: The redirection URL that the user is redirected to after the user agrees to authorize.
        :param scopes: The authorization scope.
        :param authState: The unique ID generated by the merchant to represent the consult request.
        :param terminalType: Terminal type of which the merchant service applies to.
        :param osType: The OS type.
        :param osVersion: The OS version.
        :param merchantRegion: The country or region where the merchant or secondary merchant operates the business.
        :param authClientId: The unique ID of the secondary merchant to which the user grants resource access permission.

        """
        endpoint = "v1/authorizations/consult"
        data = {
            "customerBelongsTo": customerBelongsTo,
            "authRedirectUrl": authRedirectUrl,
            "scopes": scopes,
            "authState": authState,
            "terminalType": terminalType,
            "osType": osType,
            "osVersion": osVersion,
            "merchantRegion": merchantRegion,
            "authClientId": self.client_id,
        }
        return self.post(endpoint, data)


class Payment(AntomCore):
    def pay(
        self,
        productCode,
        paymentRequestId,
        order,
        paymentAmount,
        paymentMethod,
        paymentRedirectUrl,
        settlementStrategy,
        env,
        paymentFactor=None,
        paymentExpiryTime=None,
        paymentNotifyUrl=None,
        userRegion=None,
        creditPayPlan=None,
        appId=None,
        merchantRegion=None,
    ):
        """
        Use this API to get the cashier page address.

        :param productCode: Represents the payment product that is being used, which is stipulated in the contract.
        :param paymentRequestId: The unique ID assigned by a merchant to identify a payment request. Alipay uses this field for idempotence control.
        :param order: The order information, such as buyer, merchant, goods, amount, shipping information, and purchase environment.
        :param paymentAmount: The payment amount that the merchant requests to receive in the order currency.
        :param paymentMethod: The payment method that is used to collect the payment by the merchant or acquirer.
        :param paymentRedirectUrl: The merchant page URL that the user is redirected to after the payment is completed.
        :param settlementStrategy: The settlement strategy for the payment request.
        :param env: Information about the environment where the order is placed, such as the device information.
        :param paymentFactor: Factors that impact the payment. This field is used to indicate the payment scenario.
        :param paymentExpiryTime: The payment expiration time is a specific time after which the payment will expire and the acquirer or merchant must terminate the order processing.
        :param paymentNotifyUrl: The URL that is used to receive the payment result notification.
        :param userRegion:A 2-letter country or region code based on the standard of ISO 3166 Country Codes.
        :param creditPayPlan: The credit payment plan information for this payment.
        :param appId: The unique ID that is assigned by Alipay to identify the mini program.
        :param merchantRegion: The country or region where the merchant operates the business. The parameter is a 2-letter country or region code that follows ISO 3166 Country Codes standard.
        """
        endpoint = "v1/payments/pay"
        data = {
            "productCode": productCode,
            "paymentRequestId": paymentRequestId,
            "order": order,
            "paymentAmount": paymentAmount,
            "paymentMethod": paymentMethod,
            "paymentRedirectUrl": paymentRedirectUrl,
            "settlementStrategy": settlementStrategy,
            "env": env,
            "paymentFactor": paymentFactor,
            "paymentExpiryTime": paymentExpiryTime,
            "paymentNotifyUrl": paymentNotifyUrl,
            "userRegion": userRegion,
            "creditPayPlan": creditPayPlan,
            "appId": appId,
            "merchantRegion": merchantRegion,
        }
        return self.post(endpoint, data)

    def inquiry(self, paymentRequestId=None, paymentId=None):
        """
        Use this API to inquire about the transaction status and other information about a previously submitted payment request.

        :param paymentRequestId: The unique ID that is assigned by a merchant to identify a payment request.
        :param paymentId: The unique ID that is assigned by Alipay to identify a payment.
        """
        endpoint = "v1/payments/inquiryPayment"

        data = {"paymentRequestId": paymentRequestId, "paymentId": paymentId}

        return self.post(endpoint, data)
