# Generated by Django 5.1.6 on 2025-08-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfiransms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='browser',
        ),
    ]
