# coding: utf-8

"""
    Onboarding Buddy API

    This document details all the available operations in the Onboarding Buddy API specification

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from onboarding_buddy_client.models.generate_image_request_m import GenerateImageRequestM

class TestGenerateImageRequestM(unittest.TestCase):
    """GenerateImageRequestM unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateImageRequestM:
        """Test GenerateImageRequestM
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateImageRequestM`
        """
        model = GenerateImageRequestM()
        if include_optional:
            return GenerateImageRequestM(
                correlation_id = '',
                idempotency_key = '',
                prompt = ''
            )
        else:
            return GenerateImageRequestM(
        )
        """

    def testGenerateImageRequestM(self):
        """Test GenerateImageRequestM"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
