
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-08-11T15:57:23+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6474f62cc0ccc07ddca65f31d028041f8c07d4e2",
 "version": "1.4.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
