# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `X-Firewall-Auth-Token` for all the firewall methods and `rime-api-key` for all other methods.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MonitorDifferenceFromTarget(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'difference': 'DifferenceFromTargetDifference',
        'target': 'DifferenceFromTargetTarget'
    }

    attribute_map = {
        'difference': 'difference',
        'target': 'target'
    }

    def __init__(self, difference=None, target=None):  # noqa: E501
        """MonitorDifferenceFromTarget - a model defined in Swagger"""  # noqa: E501
        self._difference = None
        self._target = None
        self.discriminator = None
        if difference is not None:
            self.difference = difference
        if target is not None:
            self.target = target

    @property
    def difference(self):
        """Gets the difference of this MonitorDifferenceFromTarget.  # noqa: E501


        :return: The difference of this MonitorDifferenceFromTarget.  # noqa: E501
        :rtype: DifferenceFromTargetDifference
        """
        return self._difference

    @difference.setter
    def difference(self, difference):
        """Sets the difference of this MonitorDifferenceFromTarget.


        :param difference: The difference of this MonitorDifferenceFromTarget.  # noqa: E501
        :type: DifferenceFromTargetDifference
        """

        self._difference = difference

    @property
    def target(self):
        """Gets the target of this MonitorDifferenceFromTarget.  # noqa: E501


        :return: The target of this MonitorDifferenceFromTarget.  # noqa: E501
        :rtype: DifferenceFromTargetTarget
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this MonitorDifferenceFromTarget.


        :param target: The target of this MonitorDifferenceFromTarget.  # noqa: E501
        :type: DifferenceFromTargetTarget
        """

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MonitorDifferenceFromTarget, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MonitorDifferenceFromTarget):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
