from enum import Enum


class EnvironmentVariable(Enum):
    ENVIRONMENT = "ENVIRONMENT"
    AZURE_KEY_VAULT_URL = "AZURE_KEY_VAULT_URL"
    AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
    AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
    AZURE_TENANT_ID = "AZURE_TENANT_ID"


class EnvironmentSecret(Enum):
    APPLICATION_NAME = "APPLICATION-NAME"
    SENTRY_URL = "SENTRY-URL"
    MONGO_DB_CONNECTION_STRING = "MONGO-DB-CONNECTION-STRING"
    DATABASE_NAME = "DATABASE-NAME"
    DISCORD_BOT_TOKEN = "DISCORD-BOT-TOKEN"
    WISE_PRIMARY_ACCOUNT_API_KEY = "WISE-PRIMARY-ACCOUNT-API-KEY"
    WISE_SECONDARY_ACCOUNT_API_KEY = "WISE-SECONDARY-ACCOUNT-API-KEY"
    ENTRA_ID_CLIENT_ID = "ENTRA-ID-CLIENT-ID"
    ENTRA_ID_TENANT_ID = "ENTRA-ID-TENANT-ID"
    TWILIO_AUTH_TOKEN = "TWILIO-AUTH-TOKEN"
    TWILIO_ACCOUNT_SID = "TWILIO-ACCOUNT-SID"
    TWILIO_WHATSAPP_NUMBER = "TWILIO-WHATSAPP-NUMBER"
    TWILIO_SMS_NUMBER = "TWILIO-SMS-NUMBER"
    OPEN_AI_API_KEY = "OPEN-AI-API-KEY"
