import abc
from abc import abstractmethod
from pathlib import Path

class BaseTokenManager(metaclass=abc.ABCMeta):
    file_name: Path | None
    logs_path: Path | None
    data_path: Path | None
    def __init__(self) -> None: ...
    def get_totp(self, totp_key: str) -> str: ...
    def set_access_token_file_name(self, path_name: str, unique_id: str) -> None: ...
    @abstractmethod
    def get_token(self) -> str: ...
    @abstractmethod
    def set_token(self, token: str) -> None: ...
    def initialize(self) -> None: ...
