# Code generated by cnb.cool/cnb/sdk/cnb-sdk-generator. DO NOT EDIT.
# versions:
#    cnb-sdk-generator: 1.0.2
# source: https://api.cnb.cool/swagger.json
from .activities import ActivitiesService
from .ai import AiService
from .artifactory import ArtifactoryService
from .assets import AssetsService
from .build import BuildService
from .collaborators import CollaboratorsService
from .contributors import ContributorsService
from .followers import FollowersService
from .git import GitService
from .gitsettings import GitsettingsService
from .issues import IssuesService
from .knowledgebase import KnowledgebaseService
from .missions import MissionsService
from .organizations import OrganizationsService
from .pulls import PullsService
from .releases import ReleasesService
from .repocontributor import RepocontributorService
from .repolabels import RepolabelsService
from .repositories import RepositoriesService
from .starring import StarringService
from .users import UsersService
from .workspace import WorkspaceService

class CNBServices:
	def __init__(self, client):
		self.client = client
		self.activities = ActivitiesService(client)
		self.ai = AiService(client)
		self.artifactory = ArtifactoryService(client)
		self.assets = AssetsService(client)
		self.build = BuildService(client)
		self.collaborators = CollaboratorsService(client)
		self.contributors = ContributorsService(client)
		self.followers = FollowersService(client)
		self.git = GitService(client)
		self.gitsettings = GitsettingsService(client)
		self.issues = IssuesService(client)
		self.knowledgebase = KnowledgebaseService(client)
		self.missions = MissionsService(client)
		self.organizations = OrganizationsService(client)
		self.pulls = PullsService(client)
		self.releases = ReleasesService(client)
		self.repocontributor = RepocontributorService(client)
		self.repolabels = RepolabelsService(client)
		self.repositories = RepositoriesService(client)
		self.starring = StarringService(client)
		self.users = UsersService(client)
		self.workspace = WorkspaceService(client)
