# Code generated by cnb.cool/cnb/sdk/cnb-sdk-generator. DO NOT EDIT.
# versions:
#    cnb-sdk-generator: 1.0.2
# source: https://api.cnb.cool/swagger.json

from typing import Optional
from .models import dto
from .models import http
class UsersService:    
	def __init__(self, client):
		self._client = client

	# 查询当前用户用户拥有指定权限的所有资源列表。List resources that the current user has specified permissions for.
	def auto_complete_source(self,
	    source_type: Optional[str] = None,
		page: Optional[int] = None,
		page_size: Optional[int] = None,
		search: Optional[str] = None,
		access: Optional[str] = None,
		order_by: Optional[str] = None,
		desc: Optional[bool] = None,
		) -> list[str]:
		u = "/user/autocomplete_source" % ()

		query_params = {
			"source_type": source_type,
			"page": page,
			"page_size": page_size,
			"search": search,
			"access": access,
			"order_by": order_by,
			"desc": desc,
			}
		data = self._client.request(
			method="GET", 
			endpoint=u,
			params=query_params,
			)
		return [str.safe_parse(item) for item in data]
		
	# 获取指定用户的详情信息。Get detailed information for a specified user.
	def get_user_info(self,
	    ) -> dto.UsersResultForSelf:
		u = "/user" % ()

		data = self._client.request(
			method="GET", 
			endpoint=u,
			)
		return dto.UsersResultForSelf.safe_parse(data)
		
	# 获取指定用户的详情信息。Get detailed information for a specified user.
	def get_user_info_by_name(self,
		username: str,
	    ) -> dto.UsersResult:
		u = "/users/%s" % (username, )

		data = self._client.request(
			method="GET", 
			endpoint=u,
			)
		return dto.UsersResult.safe_parse(data)
		
	# 更新指定用户的详情信息。Updates the specified user's profile information.
	def update_user_info(self,
	    body_params: http.UpdateUserInfoPayload,
		):
		u = "/user" % ()

		data = self._client.request(
			method="POST", 
			endpoint=u,
			json=body_params.to_dict(),
			)
		return 
		
	