from datetime import date
from typing import Any

def fInt(value: Any) -> tuple[bool, int | None]: ...
def fFloat(value: Any) -> tuple[bool, float | None]: ...
def fBool(value: Any) -> tuple[bool, bool | None]: ...
def fDate(value: Any, fmt: str = '%Y-%m-%d') -> tuple[bool, date | None]: ...
def fEnum(value: Any, choices: set[str] | list[str]) -> tuple[bool, str | None]: ...
def fJSON(value: Any) -> tuple[bool, dict | None]: ...
