# Generated by Django 5.2 on 2025-07-07 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='Name of the model being processed', max_length=100)),
                ('operation', models.CharField(choices=[('update', 'Update'), ('delete', 'Delete')], help_text='Type of bulk operation', max_length=20)),
                ('total_records', models.IntegerField(help_text='Total number of records to process')),
                ('processed_records', models.IntegerField(default=0, help_text='Number of records processed so far')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if the operation failed')),
                ('task_key', models.CharField(db_index=True, help_text='Unique key to prevent duplicate operations', max_length=255)),
                ('operation_data', models.JSONField(default=dict, help_text='Serialized data about the operation (fields, values, etc.)')),
                ('user', models.ForeignKey(help_text='User who initiated the bulk operation', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Task',
                'verbose_name_plural': 'Bulk Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='nominopolit_user_id_d3206e_idx'), models.Index(fields=['task_key'], name='nominopolit_task_ke_34b627_idx'), models.Index(fields=['created_at'], name='nominopolit_created_707ca9_idx')],
            },
        ),
    ]
