# Generated by Django 5.2.4 on 2025-07-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominopolitan', '0003_alter_bulktask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktask',
            name='async_backend',
            field=models.CharField(blank=True, choices=[('q2', 'Django-Q2'), ('celery', 'Celery')], help_text='Async backend used for this task', max_length=20, null=True),
        ),
    ]
