from setuptools import setup, find_packages

setup(
    name="traauto",
    version="0.1.0",
    description="AutoML with Enhanced Track-Rail Algorithm, meta-learning, feature engineering, explainability, and smart ensemble fusion.",
    author="Dasari Ranga Eswar",
    author_email="rangaeswar890@gmail.com",
    url="https://github.com/eswaroy/automl_tra",  
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "pandas",
        "scikit-learn",
        "joblib",
        "psutil",
        # For optional features
        "optuna>=2.0.0; extra == 'optuna'",
        "torch; extra == 'torch'",
        "xgboost; extra == 'xgboost'",
        "lightgbm; extra == 'lightgbm'",
        "shap; extra == 'shap'",
        "lime; extra == 'lime'",
        "imbalanced-learn; extra == 'imblearn'",
    ],
    python_requires=">=3.7",
    include_package_data=True,
    license="MIT",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Operating System :: OS Independent",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    extras_require={
        "optuna": ["optuna>=2.0.0"],
        "torch": ["torch"],
        "xgboost": ["xgboost"],
        "lightgbm": ["lightgbm"],
        "shap": ["shap"],
        "lime": ["lime"],
        "imblearn": ["imbalanced-learn"],
    },
)
