# coding: utf-8

"""
    Financial Reports API

    API for accessing company filings, financial data, industry classifications, and related information.

    The version of the OpenAPI document: 1.0.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.sources_api import SourcesApi


class TestSourcesApi(unittest.IsolatedAsyncioTestCase):
    """SourcesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SourcesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_sources_list(self) -> None:
        """Test case for sources_list

        List Data Sources
        """
        pass

    async def test_sources_retrieve(self) -> None:
        """Test case for sources_retrieve

        Retrieve Data Source
        """
        pass


if __name__ == '__main__':
    unittest.main()
