# coding: utf-8

"""
    Financial Reports API

    API for accessing company filings, financial data, industry classifications, and related information.

    The version of the OpenAPI document: 1.0.0
    Contact: api@financialreports.eu
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from financial_reports_generated_client.api.filing_types_api import FilingTypesApi


class TestFilingTypesApi(unittest.IsolatedAsyncioTestCase):
    """FilingTypesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FilingTypesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_filing_types_list(self) -> None:
        """Test case for filing_types_list

        List Filing Types
        """
        pass

    async def test_filing_types_retrieve(self) -> None:
        """Test case for filing_types_retrieve

        Retrieve Filing Type
        """
        pass


if __name__ == '__main__':
    unittest.main()
