TEST_SIZE = 1 / 3
TEST_VALIDATION_ACCURACY_GOAL = 0.97
# points with uncertainty higher than UNCERTAINTY_CUTOFF% are no more than UNCERTAINTY_SLICE% of the sample
PROBABILITY_CUTOFF = 0.90
PROBABILITY_SLICE_GOAL = 0.05
NUMBER_OF_TREES = 200
SIGMA_1 = 0.68
SIGMA_2 = 0.95
CLTYPE = 'CLSMBG'
