from enum import Enum


class ClaimRequestType(Enum):
    REQ_CREDENTIAL = "REQ_CREDENTIAL"
    REQ_PRESENTATION = "REQ_PRESENTATION"
    DID_INIT = "DID_INIT"
    REQ_REVOCATION = "REQ_REVOCATION"


class ClaimResponseType(Enum):
    DID_AUTH = "DID_AUTH"
    CREDENTIAL_RESULT = "CREDENTIAL_RESULT"
    RES_REVOCATION = "RES_REVOCATION"
