# Color Constants Codes For Changing Foreground Color Of Terminal
BLACK_FOREGROUND = "[30m"
BRIGHT_BLACK_FOREGROUND = "[90m"

RED_FOREGROUND = "[31m"
BRIGHT_RED_FOREGROUND = "[91m"

GREEN_FOREGROUND = "[32m"
BRIGHT_GREEN_FOREGROUND = "[92m"

YELLOW_FOREGROUND = "[33m"
BRIGHT_YELLOW_FOREGROUND = "[93m"

BLUE_FOREGROUND = "[34m"
BRIGHT_BLUE_FOREGROUND = "[94m"

MAGENTA_FOREGROUND = "[35m"
BRIGHT_MAGENTA_FOREGROUND = "[95m"

CYAN_FOREGROUND = "[36m"
BRIGHT_CYAN_FOREGROUND = "[96m"

WHITE_FOREGROUND = "[37m"
BRIGHT_WHITE_FOREGROUND = "[97m"


# Color Constants Codes For Changing Background Color Of Terminal
BLACK_BACKGROUND = "[40m"
BRIGHT_BLACK_BACKGROUND = "[100m"

RED_BACKGROUND = "[41m"
BRIGHT_RED_BACKGROUND = "[101m"

GREEN_BACKGROUND = "[42m"
BRIGHT_GREEN_BACKGROUND = "[102m"

YELLOW_BACKGROUND = "[43m"
BRIGHT_YELLOW_BACKGROUND = "[103m"

BLUE_BACKGROUND = "[44m"
BRIGHT_BLUE_BACKGROUND = "[104m"

MAGENTA_BACKGROUND = "[45m"
BRIGHT_MAGENTA_BACKGROUND = "[105m"

CYAN_BACKGROUND = "[46m"
BRIGHT_CYAN_BACKGROUND = "[106m"

WHITE_BACKGROUND = "[47m"
BRIGHT_WHITE_BACKGROUND = "[107m"
