# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.scheduled_ct_parameters import ScheduledCTParameters

class TestScheduledCTParameters(unittest.TestCase):
    """ScheduledCTParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduledCTParameters:
        """Test ScheduledCTParameters
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduledCTParameters`
        """
        model = ScheduledCTParameters()
        if include_optional:
            return ScheduledCTParameters(
                eval_data_info = ri.apiclient.models.data_info.DataInfo(
                    connection_info = ri.apiclient.models.connection_info.ConnectionInfo(
                        data_collector = ri.apiclient.models.data_collector_info.DataCollectorInfo(
                            data_stream_id = ri.apiclient.models.id.ID(
                                uuid = '', ), ), 
                        data_file = ri.apiclient.models.data_file_info.DataFileInfo(
                            data_type = 'DATA_TYPE_UNSPECIFIED', 
                            path = '', ), 
                        data_loading = ri.apiclient.models.data_loading_info.DataLoadingInfo(
                            data_endpoint_integration_id = ri.apiclient.models.id.ID(
                                uuid = '', ), 
                            load_func_name = '', 
                            loader_kwargs_json = '', 
                            path = '', ), 
                        databricks = ri.apiclient.models.databricks_info.DatabricksInfo(
                            table_name = '', ), 
                        hugging_face = ri.apiclient.models.hugging_face_data_info.HuggingFaceDataInfo(
                            dataset_uri = '', 
                            loading_params_json = '', 
                            split_name = '', ), ), 
                    data_params = ri.apiclient.models.data_params.DataParams(
                        categorical_features = [
                            ''
                            ], 
                        class_names = [
                            ''
                            ], 
                        experimental_fields = {
                            'key' : None
                            }, 
                        feature_type_path = '', 
                        features_not_in_model = [
                            ''
                            ], 
                        image_features = [
                            ''
                            ], 
                        image_load_path = '', 
                        intersections = [
                            ri.apiclient.models.feature_intersection.FeatureIntersection(
                                features = [
                                    ''
                                    ], )
                            ], 
                        label_col = '', 
                        loading_kwargs = '', 
                        nrows = '', 
                        nrows_per_time_bin = '', 
                        prompt_col = '', 
                        protected_features = [
                            ''
                            ], 
                        ranking_info = ri.apiclient.models.ranking_info.RankingInfo(
                            drop_query_id = True, 
                            nqueries = '', 
                            nrows_per_query = '', 
                            query_col = '', ), 
                        sample = True, 
                        text_features = [
                            ''
                            ], 
                        timestamp_col = '', ), ),
                eval_data_integration_id = ri.apiclient.models.id.ID(
                    uuid = '', ),
                eval_pred_info = ri.apiclient.models.pred_info.PredInfo(
                    connection_info = ri.apiclient.models.connection_info.ConnectionInfo(
                        data_collector = ri.apiclient.models.data_collector_info.DataCollectorInfo(
                            data_stream_id = ri.apiclient.models.id.ID(
                                uuid = '', ), ), 
                        data_file = ri.apiclient.models.data_file_info.DataFileInfo(
                            data_type = 'DATA_TYPE_UNSPECIFIED', 
                            path = '', ), 
                        data_loading = ri.apiclient.models.data_loading_info.DataLoadingInfo(
                            data_endpoint_integration_id = ri.apiclient.models.id.ID(
                                uuid = '', ), 
                            load_func_name = '', 
                            loader_kwargs_json = '', 
                            path = '', ), 
                        databricks = ri.apiclient.models.databricks_info.DatabricksInfo(
                            table_name = '', ), 
                        hugging_face = ri.apiclient.models.hugging_face_data_info.HuggingFaceDataInfo(
                            dataset_uri = '', 
                            loading_params_json = '', 
                            split_name = '', ), ), 
                    pred_params = ri.apiclient.models.prediction_params.PredictionParams(
                        experimental_fields = {
                            'key' : None
                            }, 
                        pred_col = '', 
                        timestamp_col = '', ), ),
                eval_pred_integration_id = ri.apiclient.models.id.ID(
                    uuid = '', )
            )
        else:
            return ScheduledCTParameters(
        )
        """

    def testScheduledCTParameters(self):
        """Test ScheduledCTParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()