# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.yara_server_config import YaraServerConfig

class TestYaraServerConfig(unittest.TestCase):
    """YaraServerConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> YaraServerConfig:
        """Test YaraServerConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `YaraServerConfig`
        """
        model = YaraServerConfig()
        if include_optional:
            return YaraServerConfig(
                rime_yara_git_ref = '',
                yara_server_image = ''
            )
        else:
            return YaraServerConfig(
        )
        """

    def testYaraServerConfig(self):
        """Test YaraServerConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()