# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.api.detection_api import DetectionApi


class TestDetectionApi(unittest.TestCase):
    """DetectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DetectionApi()

    def tearDown(self) -> None:
        pass

    def test_list_detection_events(self) -> None:
        """Test case for list_detection_events

        ListDetectionEvents
        """
        pass


if __name__ == '__main__':
    unittest.main()