# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.api.data_collector_api import DataCollectorApi


class TestDataCollectorApi(unittest.TestCase):
    """DataCollectorApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataCollectorApi()

    def tearDown(self) -> None:
        pass

    def test_get_datapoints(self) -> None:
        """Test case for get_datapoints

        GetDatapoints
        """
        pass

    def test_get_predictions(self) -> None:
        """Test case for get_predictions

        GetPredictions
        """
        pass

    def test_register_data_stream(self) -> None:
        """Test case for register_data_stream

        RegisterDataStream
        """
        pass

    def test_store_datapoints(self) -> None:
        """Test case for store_datapoints

        StoreDatapoints
        """
        pass

    def test_store_predictions(self) -> None:
        """Test case for store_predictions

        StorePredictions
        """
        pass


if __name__ == '__main__':
    unittest.main()