# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.get_model_directory_upload_urls_request import GetModelDirectoryUploadURLsRequest

class TestGetModelDirectoryUploadURLsRequest(unittest.TestCase):
    """GetModelDirectoryUploadURLsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetModelDirectoryUploadURLsRequest:
        """Test GetModelDirectoryUploadURLsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetModelDirectoryUploadURLsRequest`
        """
        model = GetModelDirectoryUploadURLsRequest()
        if include_optional:
            return GetModelDirectoryUploadURLsRequest(
                directory_name = '',
                relative_file_paths = [
                    ''
                    ],
                upload_path = ''
            )
        else:
            return GetModelDirectoryUploadURLsRequest(
                directory_name = '',
                relative_file_paths = [
                    ''
                    ],
        )
        """

    def testGetModelDirectoryUploadURLsRequest(self):
        """Test GetModelDirectoryUploadURLsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()