# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.continuous_test_run_progress import ContinuousTestRunProgress

class TestContinuousTestRunProgress(unittest.TestCase):
    """ContinuousTestRunProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContinuousTestRunProgress:
        """Test ContinuousTestRunProgress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContinuousTestRunProgress`
        """
        model = ContinuousTestRunProgress()
        if include_optional:
            return ContinuousTestRunProgress(
                bin_end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bin_start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                test_run = ri.apiclient.models.test_run_progress.TestRunProgress(
                    status = 'TEST_TASK_STATUS_UNSPECIFIED', 
                    test_batches = [
                        ri.apiclient.models.test_batch_progress.TestBatchProgress(
                            type = '', )
                        ], 
                    test_run_id = '', )
            )
        else:
            return ContinuousTestRunProgress(
        )
        """

    def testContinuousTestRunProgress(self):
        """Test ContinuousTestRunProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()