# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `rime-api-key` header.

    The version of the OpenAPI document: 1.0
    Contact: dev@robustintelligence.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from ri.apiclient.models.model import Model

class TestModel(unittest.TestCase):
    """Model unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model:
        """Test Model
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model`
        """
        model = Model()
        if include_optional:
            return Model(
                creation_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator_id = ri.apiclient.models.id.ID(
                    uuid = '', ),
                external_id = '',
                integration_id = ri.apiclient.models.id.ID(
                    uuid = '', ),
                model_endpoint_integration_id = ri.apiclient.models.id.ID(
                    uuid = '', ),
                model_id = ri.apiclient.models.id.ID(
                    uuid = '', ),
                model_info = ri.apiclient.models.model_info.ModelInfo(
                    hugging_face = ri.apiclient.models.hugging_face_model_info.HuggingFaceModelInfo(
                        kwargs = '', 
                        model_uri = '', ), 
                    model_path = ri.apiclient.models.model_path_info.ModelPathInfo(
                        path = '', ), ),
                name = '',
                project_ids = [
                    ri.apiclient.models.id.ID(
                        uuid = '', )
                    ],
                user_metadata = ri.apiclient.models.metadata.Metadata(
                    extra_info = '', 
                    tags = [
                        ''
                        ], ),
                validity_status = 'VALIDITY_STATUS_UNSPECIFIED',
                validity_status_message = ''
            )
        else:
            return Model(
        )
        """

    def testModel(self):
        """Test Model"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()