"""Constants file."""

PROG_NAME = "edata"
DEFAULT_STORAGE_DIR = "edata.storage"

# Attributes definition for backward compatibility
ATTRIBUTES = {
    "cups": None,
    "contract_p1_kW": "kW",
    "contract_p2_kW": "kW",
    "yesterday_kWh": "kWh",
    "yesterday_hours": "h",
    "yesterday_p1_kWh": "kWh",
    "yesterday_p2_kWh": "kWh",
    "yesterday_p3_kWh": "kWh",
    "yesterday_surplus_kWh": "kWh",
    "yesterday_surplus_p1_kWh": "kWh",
    "yesterday_surplus_p2_kWh": "kWh",
    "yesterday_surplus_p3_kWh": "kWh",
    "last_registered_date": None,
    "last_registered_day_kWh": "kWh",
    "last_registered_day_hours": "h",
    "last_registered_day_p1_kWh": "kWh",
    "last_registered_day_p2_kWh": "kWh",
    "last_registered_day_p3_kWh": "kWh",
    "last_registered_day_surplus_kWh": "kWh",
    "last_registered_day_surplus_p1_kWh": "kWh",
    "last_registered_day_surplus_p2_kWh": "kWh",
    "last_registered_day_surplus_p3_kWh": "kWh",
    "month_kWh": "kWh",
    "month_daily_kWh": "kWh",
    "month_days": "d",
    "month_p1_kWh": "kWh",
    "month_p2_kWh": "kWh",
    "month_p3_kWh": "kWh",
    "month_surplus_kWh": "kWh",
    "month_surplus_p1_kWh": "kWh",
    "month_surplus_p2_kWh": "kWh",
    "month_surplus_p3_kWh": "kWh",
    "month_€": "€",
    "last_month_kWh": "kWh",
    "last_month_daily_kWh": "kWh",
    "last_month_days": "d",
    "last_month_p1_kWh": "kWh",
    "last_month_p2_kWh": "kWh",
    "last_month_p3_kWh": "kWh",
    "last_month_surplus_kWh": "kWh",
    "last_month_surplus_p1_kWh": "kWh",
    "last_month_surplus_p2_kWh": "kWh",
    "last_month_surplus_p3_kWh": "kWh",
    "last_month_€": "€",
    "max_power_kW": "kW",
    "max_power_date": None,
    "max_power_mean_kW": "kW",
    "max_power_90perc_kW": "kW",
}
