def extract_codeblocks(text: str) -> str: ...
def omit_codeblocks(text: str) -> str: ...
def strip_markdown_formatting(text: str) -> str: ...
def omit_urls(text: str) -> str: ...
def normalize_markdown(text: str) -> str: ...