# 📚 STRUCT

from .STRUCT_BASE import STRUCT_BASE
from .STRUCT_ATTRIBUTES import STRUCT_ATTRIBUTES
from .STRUCT_LISTS import STRUCT_LISTS
from .STRUCT_DICTIONARIES import STRUCT_DICTIONARIES
from .STRUCT_CONVERT import STRUCT_CONVERT

class STRUCT(
    STRUCT_CONVERT,
    STRUCT_DICTIONARIES,
    STRUCT_LISTS,
    STRUCT_ATTRIBUTES,
    STRUCT_BASE
): 
    pass
  