# This file automatically generated by
#    /home/runner/work/analytics-python-client/analytics-python-client/./couchbase_analytics_version.py
# at
#    2025-08-08 15:06:45.161869
__version__ = '1.0.0'
