friend(alina, anna).
friend(alina, clara).
friend(alina, emily).
friend(alina, lara).
friend(alina, natalie).
friend(alina, valentina).
friend(alina, daniel).
friend(alina, emil).
friend(alina, jan).
friend(alina, jonathan).
friend(alina, leo).
friend(alina, matthias).
friend(alina, nico).
friend(alina, raphael).
friend(alina, rene).
friend(alina, sebastian).
friend(alina, theodor).
friend(alina, thomas).
friend(amelie, charlotte).
friend(amelie, mia).
friend(amelie, paula).
friend(amelie, sofia).
friend(amelie, vanessa).
friend(amelie, adrian).
friend(amelie, fabian).
friend(amelie, gabriel).
friend(amelie, jonas).
friend(amelie, leon).
friend(amelie, lukas).
friend(amelie, oskar).
friend(amelie, samuel).
friend(anastasia, angelina).
friend(anastasia, clara).
friend(anastasia, claudia).
friend(anastasia, elena).
friend(anastasia, ella).
friend(anastasia, emilia2).
friend(anastasia, emma).
friend(anastasia, gertrude).
friend(anastasia, hannah).
friend(anastasia, helga).
friend(anastasia, isabella).
friend(anastasia, karin).
friend(anastasia, katharina).
friend(anastasia, larissa).
friend(anastasia, lena).
friend(anastasia, leonie).
friend(anastasia, marie).
friend(anastasia, marlene).
friend(anastasia, sarah).
friend(anastasia, valerie).
friend(anastasia, dominik).
friend(anastasia, florian).
friend(anastasia, julian).
friend(anastasia, konstantin).
friend(anastasia, lorenz).
friend(anastasia, marcel).
friend(anastasia, maximilian).
friend(anastasia, michael).
friend(anastasia, moritz).
friend(anastasia, noah).
friend(anastasia, patrick).
friend(anastasia, sebastian).
friend(anastasia, thomas).
friend(anastasia, tobias).
friend(anastasia, valentin).
friend(anastasia, vincent).
friend(angelina, clara).
friend(angelina, emma).
friend(angelina, helga).
friend(angelina, marlene).
friend(angelina, sarah).
friend(angelina, michael).
friend(angelina, sebastian).
friend(anna, clara).
friend(anna, emily).
friend(anna, emma).
friend(anna, lara).
friend(anna, natalie).
friend(anna, valentina).
friend(anna, daniel).
friend(anna, emil).
friend(anna, jan).
friend(anna, jonathan).
friend(anna, leo).
friend(anna, matthias).
friend(anna, michael).
friend(anna, nico).
friend(anna, raphael).
friend(anna, rene).
friend(anna, sebastian).
friend(anna, theodor).
friend(anna, thomas).
friend(beate, nina).
friend(charlotte, johanna).
friend(charlotte, mia).
friend(charlotte, paula).
friend(charlotte, sofia).
friend(charlotte, vanessa).
friend(charlotte, adrian).
friend(charlotte, fabian).
friend(charlotte, gabriel).
friend(charlotte, jonas).
friend(charlotte, leon).
friend(charlotte, lukas).
friend(charlotte, oskar).
friend(charlotte, samuel).
friend(clara, claudia).
friend(clara, ella).
friend(clara, emilia2).
friend(clara, emily).
friend(clara, emma).
friend(clara, hannah).
friend(clara, helga).
friend(clara, isabella).
friend(clara, katharina).
friend(clara, lara).
friend(clara, lena).
friend(clara, marie).
friend(clara, marlene).
friend(clara, sarah).
friend(clara, valerie).
friend(clara, daniel).
friend(clara, dominik).
friend(clara, emil).
friend(clara, jan).
friend(clara, julian).
friend(clara, konstantin).
friend(clara, leo).
friend(clara, lorenz).
friend(clara, marcel).
friend(clara, maximilian).
friend(clara, michael).
friend(clara, moritz).
friend(clara, noah).
friend(clara, sebastian).
friend(clara, theodor).
friend(clara, thomas).
friend(clara, tobias).
friend(clara, valentin).
friend(clara, vincent).
friend(claudia, ella).
friend(claudia, emma).
friend(claudia, helga).
friend(claudia, isabella).
friend(claudia, lena).
friend(claudia, marie).
friend(claudia, marlene).
friend(claudia, sarah).
friend(claudia, dominik).
friend(claudia, marcel).
friend(claudia, michael).
friend(claudia, sebastian).
friend(claudia, tobias).
friend(claudia, vincent).
friend(elena, ella).
friend(elena, emilia).
friend(elena, gertrude).
friend(elena, helga).
friend(elena, karin).
friend(elena, larissa).
friend(elena, leonie).
friend(elena, luisa).
friend(elena, magdalena).
friend(elena, marie).
friend(elena, marlene).
friend(elena, sarah).
friend(elena, selina).
friend(elena, victoria).
friend(elena, alexander).
friend(elena, benjamin).
friend(elena, david).
friend(elena, elias).
friend(elena, felix).
friend(elena, florian).
friend(elena, julian).
friend(elena, marko).
friend(elena, maximilian).
friend(elena, michael).
friend(elena, moritz).
friend(elena, patrick).
friend(elena, philipp).
friend(elena, simon).
friend(elena, tobias).
friend(ella, emilia2).
friend(ella, emma).
friend(ella, gertrude).
friend(ella, helga).
friend(ella, isabella).
friend(ella, karin).
friend(ella, katharina).
friend(ella, lena).
friend(ella, marie).
friend(ella, marlene).
friend(ella, sarah).
friend(ella, dominik).
friend(ella, florian).
friend(ella, julian).
friend(ella, konstantin).
friend(ella, marcel).
friend(ella, maximilian).
friend(ella, michael).
friend(ella, moritz).
friend(ella, noah).
friend(ella, patrick).
friend(ella, sebastian).
friend(ella, tobias).
friend(ella, vincent).
friend(emilia, gertrude).
friend(emilia, karin).
friend(emilia, leonie).
friend(emilia, luisa).
friend(emilia, magdalena).
friend(emilia, nina).
friend(emilia, nora).
friend(emilia, selina).
friend(emilia, alexander).
friend(emilia, benjamin).
friend(emilia, david).
friend(emilia, elias).
friend(emilia, felix).
friend(emilia, florian).
friend(emilia, marko).
friend(emilia, patrick).
friend(emilia, simon).
friend(emilia2, emma).
friend(emilia2, helga).
friend(emilia2, isabella).
friend(emilia2, lena).
friend(emilia2, marie).
friend(emilia2, marlene).
friend(emilia2, sarah).
friend(emilia2, dominik).
friend(emilia2, marcel).
friend(emilia2, michael).
friend(emilia2, sebastian).
friend(emilia2, tobias).
friend(emilia2, vincent).
friend(emily, lara).
friend(emily, natalie).
friend(emily, valentina).
friend(emily, christian).
friend(emily, daniel).
friend(emily, emil).
friend(emily, jan).
friend(emily, jonathan).
friend(emily, leo).
friend(emily, matthias).
friend(emily, nico).
friend(emily, raphael).
friend(emily, rene).
friend(emily, sebastian).
friend(emily, theodor).
friend(emily, thomas).
friend(emma, hannah).
friend(emma, helga).
friend(emma, isabella).
friend(emma, karin).
friend(emma, katharina).
friend(emma, lena).
friend(emma, marie).
friend(emma, marlene).
friend(emma, sarah).
friend(emma, valerie).
friend(emma, dominik).
friend(emma, emil).
friend(emma, julian).
friend(emma, konstantin).
friend(emma, leo).
friend(emma, lorenz).
friend(emma, marcel).
friend(emma, maximilian).
friend(emma, michael).
friend(emma, moritz).
friend(emma, noah).
friend(emma, sebastian).
friend(emma, theodor).
friend(emma, thomas).
friend(emma, tobias).
friend(emma, valentin).
friend(emma, vincent).
friend(gertrude, helga).
friend(gertrude, karin).
friend(gertrude, larissa).
friend(gertrude, leonie).
friend(gertrude, luisa).
friend(gertrude, magdalena).
friend(gertrude, marie).
friend(gertrude, marlene).
friend(gertrude, sarah).
friend(gertrude, selina).
friend(gertrude, victoria).
friend(gertrude, alexander).
friend(gertrude, benjamin).
friend(gertrude, david).
friend(gertrude, elias).
friend(gertrude, felix).
friend(gertrude, florian).
friend(gertrude, julian).
friend(gertrude, marko).
friend(gertrude, maximilian).
friend(gertrude, moritz).
friend(gertrude, patrick).
friend(gertrude, philipp).
friend(gertrude, simon).
friend(hannah, helga).
friend(hannah, isabella).
friend(hannah, lena).
friend(hannah, marie).
friend(hannah, marlene).
friend(hannah, sarah).
friend(hannah, marcel).
friend(hannah, michael).
friend(hannah, sebastian).
friend(helena, laura).
friend(helena, lina).
friend(helena, lisa).
friend(helena, nina).
friend(helena, nora).
friend(helena, sophie).
friend(helena, adam).
friend(helena, jakob).
friend(helena, luca).
friend(helena, oliver).
friend(helga, isabella).
friend(helga, karin).
friend(helga, katharina).
friend(helga, lena).
friend(helga, marie).
friend(helga, marlene).
friend(helga, sarah).
friend(helga, valerie).
friend(helga, dominik).
friend(helga, florian).
friend(helga, julian).
friend(helga, konstantin).
friend(helga, lorenz).
friend(helga, marcel).
friend(helga, maximilian).
friend(helga, michael).
friend(helga, moritz).
friend(helga, noah).
friend(helga, patrick).
friend(helga, sebastian).
friend(helga, tobias).
friend(helga, valentin).
friend(helga, vincent).
friend(isabella, katharina).
friend(isabella, lena).
friend(isabella, marie).
friend(isabella, marlene).
friend(isabella, sarah).
friend(isabella, valerie).
friend(isabella, dominik).
friend(isabella, julian).
friend(isabella, konstantin).
friend(isabella, leo).
friend(isabella, lorenz).
friend(isabella, marcel).
friend(isabella, maximilian).
friend(isabella, michael).
friend(isabella, moritz).
friend(isabella, noah).
friend(isabella, sebastian).
friend(isabella, thomas).
friend(isabella, tobias).
friend(isabella, valentin).
friend(isabella, vincent).
friend(johanna, vanessa).
friend(johanna, lukas).
friend(johanna, oskar).
friend(johanna, samuel).
friend(julia, laura).
friend(julia, lina).
friend(julia, lisa).
friend(julia, nina).
friend(julia, nora).
friend(julia, adam).
friend(julia, luca).
friend(julia, oliver).
friend(karin, larissa).
friend(karin, leonie).
friend(karin, magdalena).
friend(karin, marie).
friend(karin, marlene).
friend(karin, sarah).
friend(karin, selina).
friend(karin, alexander).
friend(karin, benjamin).
friend(karin, elias).
friend(karin, felix).
friend(karin, florian).
friend(karin, julian).
friend(karin, marko).
friend(karin, maximilian).
friend(karin, michael).
friend(karin, moritz).
friend(karin, patrick).
friend(karin, simon).
friend(karin, tobias).
friend(katharina, lena).
friend(katharina, marie).
friend(katharina, marlene).
friend(katharina, sarah).
friend(katharina, dominik).
friend(katharina, julian).
friend(katharina, konstantin).
friend(katharina, marcel).
friend(katharina, michael).
friend(katharina, noah).
friend(katharina, sebastian).
friend(katharina, tobias).
friend(katharina, vincent).
friend(lara, natalie).
friend(lara, valentina).
friend(lara, christian).
friend(lara, daniel).
friend(lara, emil).
friend(lara, jan).
friend(lara, jonathan).
friend(lara, leo).
friend(lara, matthias).
friend(lara, nico).
friend(lara, raphael).
friend(lara, rene).
friend(lara, sebastian).
friend(lara, theodor).
friend(lara, thomas).
friend(larissa, leonie).
friend(larissa, florian).
friend(larissa, patrick).
friend(laura, lea).
friend(laura, lina).
friend(laura, lisa).
friend(laura, maria).
friend(laura, nina).
friend(laura, nora).
friend(laura, olivia).
friend(laura, sophie).
friend(laura, adam).
friend(laura, jakob).
friend(laura, luca).
friend(laura, luis).
friend(laura, marko).
friend(laura, oliver).
friend(lea, lisa).
friend(lea, nina).
friend(lea, nora).
friend(lea, adam).
friend(lea, luca).
friend(lea, oliver).
friend(lena, marie).
friend(lena, marlene).
friend(lena, sarah).
friend(lena, dominik).
friend(lena, julian).
friend(lena, konstantin).
friend(lena, lorenz).
friend(lena, marcel).
friend(lena, michael).
friend(lena, moritz).
friend(lena, noah).
friend(lena, sebastian).
friend(lena, thomas).
friend(lena, tobias).
friend(lena, vincent).
friend(leonie, luisa).
friend(leonie, magdalena).
friend(leonie, nora).
friend(leonie, selina).
friend(leonie, alexander).
friend(leonie, benjamin).
friend(leonie, david).
friend(leonie, elias).
friend(leonie, felix).
friend(leonie, florian).
friend(leonie, marko).
friend(leonie, maximilian).
friend(leonie, patrick).
friend(leonie, simon).
friend(lina, lisa).
friend(lina, nina).
friend(lina, nora).
friend(lina, sophie).
friend(lina, adam).
friend(lina, jakob).
friend(lina, luca).
friend(lina, luis).
friend(lina, oliver).
friend(lisa, maria).
friend(lisa, nina).
friend(lisa, nora).
friend(lisa, olivia).
friend(lisa, sofia).
friend(lisa, sophie).
friend(lisa, adam).
friend(lisa, jakob).
friend(lisa, luca).
friend(lisa, luis).
friend(lisa, oliver).
friend(luisa, nina).
friend(luisa, nora).
friend(luisa, alexander).
friend(luisa, felix).
friend(luisa, florian).
friend(luisa, marko).
friend(magdalena, selina).
friend(magdalena, alexander).
friend(magdalena, benjamin).
friend(magdalena, elias).
friend(magdalena, felix).
friend(magdalena, florian).
friend(magdalena, marko).
friend(magdalena, patrick).
friend(magdalena, simon).
friend(maria, nina).
friend(maria, nora).
friend(maria, adam).
friend(maria, luca).
friend(maria, oliver).
friend(marie, marlene).
friend(marie, sarah).
friend(marie, dominik).
friend(marie, julian).
friend(marie, konstantin).
friend(marie, lorenz).
friend(marie, marcel).
friend(marie, maximilian).
friend(marie, michael).
friend(marie, moritz).
friend(marie, noah).
friend(marie, sebastian).
friend(marie, tobias).
friend(marie, vincent).
friend(marlene, sarah).
friend(marlene, valerie).
friend(marlene, dominik).
friend(marlene, julian).
friend(marlene, konstantin).
friend(marlene, lorenz).
friend(marlene, marcel).
friend(marlene, maximilian).
friend(marlene, michael).
friend(marlene, moritz).
friend(marlene, noah).
friend(marlene, sebastian).
friend(marlene, thomas).
friend(marlene, tobias).
friend(marlene, valentin).
friend(marlene, vincent).
friend(mia, natalie).
friend(mia, sofia).
friend(mia, vanessa).
friend(mia, fabian).
friend(mia, gabriel).
friend(mia, jonas).
friend(mia, lukas).
friend(mia, oskar).
friend(mia, samuel).
friend(natalie, valentina).
friend(natalie, vanessa).
friend(natalie, christian).
friend(natalie, daniel).
friend(natalie, emil).
friend(natalie, fabian).
friend(natalie, gabriel).
friend(natalie, jan).
friend(natalie, jonathan).
friend(natalie, leo).
friend(natalie, lukas).
friend(natalie, matthias).
friend(natalie, nico).
friend(natalie, raphael).
friend(natalie, rene).
friend(natalie, samuel).
friend(natalie, theodor).
friend(natalie, thomas).
friend(nina, nora).
friend(nina, olivia).
friend(nina, sophie).
friend(nina, adam).
friend(nina, jakob).
friend(nina, luca).
friend(nina, luis).
friend(nina, marko).
friend(nina, oliver).
friend(nora, olivia).
friend(nora, sophie).
friend(nora, adam).
friend(nora, alexander).
friend(nora, felix).
friend(nora, florian).
friend(nora, jakob).
friend(nora, luca).
friend(nora, luis).
friend(nora, marko).
friend(nora, oliver).
friend(olivia, adam).
friend(olivia, luca).
friend(olivia, oliver).
friend(paula, sofia).
friend(paula, vanessa).
friend(paula, fabian).
friend(paula, jonas).
friend(paula, lukas).
friend(paula, oskar).
friend(paula, samuel).
friend(sarah, valerie).
friend(sarah, dominik).
friend(sarah, julian).
friend(sarah, konstantin).
friend(sarah, lorenz).
friend(sarah, marcel).
friend(sarah, maximilian).
friend(sarah, michael).
friend(sarah, moritz).
friend(sarah, noah).
friend(sarah, patrick).
friend(sarah, sebastian).
friend(sarah, tobias).
friend(sarah, valentin).
friend(sarah, vincent).
friend(selina, alexander).
friend(selina, benjamin).
friend(selina, elias).
friend(selina, felix).
friend(selina, florian).
friend(selina, marko).
friend(selina, patrick).
friend(selina, simon).
friend(sofia, sophie).
friend(sofia, vanessa).
friend(sofia, adam).
friend(sofia, fabian).
friend(sofia, jonas).
friend(sofia, leon).
friend(sofia, lukas).
friend(sofia, oliver).
friend(sofia, oskar).
friend(sofia, samuel).
friend(sophie, adam).
friend(sophie, luca).
friend(sophie, oliver).
friend(valentina, daniel).
friend(valentina, emil).
friend(valentina, jan).
friend(valentina, jonathan).
friend(valentina, leo).
friend(valentina, matthias).
friend(valentina, nico).
friend(valentina, raphael).
friend(valentina, theodor).
friend(valentina, thomas).
friend(valerie, michael).
friend(valerie, sebastian).
friend(vanessa, adrian).
friend(vanessa, fabian).
friend(vanessa, gabriel).
friend(vanessa, jonas).
friend(vanessa, leon).
friend(vanessa, lukas).
friend(vanessa, oskar).
friend(vanessa, samuel).
friend(victoria, florian).
friend(adam, jakob).
friend(adam, luca).
friend(adam, luis).
friend(adam, oliver).
friend(adrian, fabian).
friend(adrian, jonas).
friend(adrian, lukas).
friend(adrian, oskar).
friend(adrian, samuel).
friend(alexander, benjamin).
friend(alexander, david).
friend(alexander, elias).
friend(alexander, felix).
friend(alexander, florian).
friend(alexander, marko).
friend(alexander, patrick).
friend(alexander, simon).
friend(benjamin, elias).
friend(benjamin, felix).
friend(benjamin, florian).
friend(benjamin, marko).
friend(benjamin, patrick).
friend(benjamin, simon).
friend(christian, daniel).
friend(christian, emil).
friend(christian, jan).
friend(christian, leo).
friend(christian, raphael).
friend(christian, thomas).
friend(daniel, emil).
friend(daniel, jan).
friend(daniel, jonathan).
friend(daniel, leo).
friend(daniel, matthias).
friend(daniel, nico).
friend(daniel, raphael).
friend(daniel, rene).
friend(daniel, sebastian).
friend(daniel, theodor).
friend(daniel, thomas).
friend(david, florian).
friend(dominik, julian).
friend(dominik, konstantin).
friend(dominik, marcel).
friend(dominik, michael).
friend(dominik, noah).
friend(dominik, sebastian).
friend(dominik, tobias).
friend(dominik, vincent).
friend(elias, felix).
friend(elias, florian).
friend(elias, marko).
friend(elias, patrick).
friend(emil, jan).
friend(emil, jonathan).
friend(emil, leo).
friend(emil, matthias).
friend(emil, michael).
friend(emil, nico).
friend(emil, raphael).
friend(emil, rene).
friend(emil, sebastian).
friend(emil, theodor).
friend(emil, thomas).
friend(fabian, gabriel).
friend(fabian, jonas).
friend(fabian, leon).
friend(fabian, lukas).
friend(fabian, oskar).
friend(fabian, samuel).
friend(felix, florian).
friend(felix, marko).
friend(felix, patrick).
friend(felix, simon).
friend(florian, marko).
friend(florian, maximilian).
friend(florian, patrick).
friend(florian, philipp).
friend(florian, simon).
friend(gabriel, jonas).
friend(gabriel, lukas).
friend(gabriel, oskar).
friend(gabriel, samuel).
friend(jakob, luca).
friend(jakob, oliver).
friend(jan, jonathan).
friend(jan, leo).
friend(jan, matthias).
friend(jan, nico).
friend(jan, raphael).
friend(jan, rene).
friend(jan, sebastian).
friend(jan, theodor).
friend(jan, thomas).
friend(jonas, leon).
friend(jonas, lukas).
friend(jonas, oskar).
friend(jonas, samuel).
friend(jonathan, leo).
friend(jonathan, matthias).
friend(jonathan, nico).
friend(jonathan, raphael).
friend(jonathan, sebastian).
friend(jonathan, theodor).
friend(jonathan, thomas).
friend(julian, konstantin).
friend(julian, marcel).
friend(julian, maximilian).
friend(julian, michael).
friend(julian, sebastian).
friend(julian, tobias).
friend(julian, vincent).
friend(konstantin, marcel).
friend(konstantin, michael).
friend(konstantin, noah).
friend(konstantin, sebastian).
friend(konstantin, thomas).
friend(konstantin, tobias).
friend(konstantin, vincent).
friend(leo, matthias).
friend(leo, michael).
friend(leo, nico).
friend(leo, raphael).
friend(leo, rene).
friend(leo, sebastian).
friend(leo, theodor).
friend(leo, thomas).
friend(leon, lukas).
friend(leon, oskar).
friend(leon, samuel).
friend(lorenz, marcel).
friend(lorenz, michael).
friend(lorenz, sebastian).
friend(lorenz, vincent).
friend(luca, luis).
friend(luca, oliver).
friend(luis, oliver).
friend(lukas, oskar).
friend(lukas, samuel).
friend(marcel, michael).
friend(marcel, moritz).
friend(marcel, noah).
friend(marcel, sebastian).
friend(marcel, thomas).
friend(marcel, tobias).
friend(marcel, vincent).
friend(marko, patrick).
friend(marko, simon).
friend(matthias, nico).
friend(matthias, raphael).
friend(matthias, rene).
friend(matthias, theodor).
friend(matthias, thomas).
friend(maximilian, michael).
friend(maximilian, patrick).
friend(maximilian, sebastian).
friend(maximilian, tobias).
friend(michael, moritz).
friend(michael, noah).
friend(michael, sebastian).
friend(michael, theodor).
friend(michael, thomas).
friend(michael, tobias).
friend(michael, valentin).
friend(michael, vincent).
friend(moritz, sebastian).
friend(moritz, tobias).
friend(moritz, vincent).
friend(nico, raphael).
friend(nico, rene).
friend(nico, theodor).
friend(nico, thomas).
friend(noah, sebastian).
friend(noah, tobias).
friend(noah, vincent).
friend(oskar, samuel).
friend(patrick, simon).
friend(raphael, rene).
friend(raphael, theodor).
friend(raphael, thomas).
friend(rene, thomas).
friend(sebastian, theodor).
friend(sebastian, thomas).
friend(sebastian, tobias).
friend(sebastian, valentin).
friend(sebastian, vincent).
friend(theodor, thomas).
friend(thomas, vincent).
friend(tobias, vincent).
