# Generated by Django 5.2.3 on 2025-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikvision', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '应用配置', 'verbose_name_plural': '应用配置'},
        ),
        migrations.AddField(
            model_name='camera',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('HOST', '服务地址'), ('APP_KEY', '应用标识'), ('APP_SECRET', '密钥凭证')], max_length=100, unique=True, verbose_name='配置项'),
        ),
    ]
