# generated by datamodel-codegen:
#   filename:  materials_category_components/entities/core/three_dimensional/void.json
#   version:   0.28.5

from __future__ import annotations

from enum import Enum
from typing import List, Literal

from pydantic import BaseModel, Field


class CoordinateShapeEnum(Enum):
    cylinder = "cylinder"
    sphere = "sphere"
    box = "box"
    triangular_prism = "triangular_prism"
    plane = "plane"


class BoxCoordinateConditionSchema(BaseModel):
    shape: Literal["box"] = Field(..., title="Coordinate Shape Enum")
    min_coordinate: List[float] = Field(..., max_length=3, min_length=3, title="coordinate 3d schema")
    max_coordinate: List[float] = Field(..., max_length=3, min_length=3, title="coordinate 3d schema")


class VoidSchema(BaseModel):
    center_coordinate: List[float] = Field(..., max_length=3, min_length=3, title="coordinate 3d schema")
    shape: BoxCoordinateConditionSchema = Field(..., title="Coordinate Conditions Schema")
    """
    Combined schema for all coordinate condition types
    """
