# Generated by Django 5.0 on 2025-07-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=255, null=True)),
                ("request", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("ref_obj", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_id", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "db_table": "request_log",
            },
        ),
    ]
