# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `X-Firewall-Auth-Token` for all the firewall methods and `rime-api-key` for all other methods.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FirewallTestCategorySeverity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_category': 'TestrunTestCategoryType',
        'risk_category_type': 'RiskscoreRiskCategoryType',
        'severity': 'RimeSeverity'
    }

    attribute_map = {
        'test_category': 'testCategory',
        'risk_category_type': 'riskCategoryType',
        'severity': 'severity'
    }

    def __init__(self, test_category=None, risk_category_type=None, severity=None):  # noqa: E501
        """FirewallTestCategorySeverity - a model defined in Swagger"""  # noqa: E501
        self._test_category = None
        self._risk_category_type = None
        self._severity = None
        self.discriminator = None
        if test_category is not None:
            self.test_category = test_category
        if risk_category_type is not None:
            self.risk_category_type = risk_category_type
        if severity is not None:
            self.severity = severity

    @property
    def test_category(self):
        """Gets the test_category of this FirewallTestCategorySeverity.  # noqa: E501


        :return: The test_category of this FirewallTestCategorySeverity.  # noqa: E501
        :rtype: TestrunTestCategoryType
        """
        return self._test_category

    @test_category.setter
    def test_category(self, test_category):
        """Sets the test_category of this FirewallTestCategorySeverity.


        :param test_category: The test_category of this FirewallTestCategorySeverity.  # noqa: E501
        :type: TestrunTestCategoryType
        """

        self._test_category = test_category

    @property
    def risk_category_type(self):
        """Gets the risk_category_type of this FirewallTestCategorySeverity.  # noqa: E501


        :return: The risk_category_type of this FirewallTestCategorySeverity.  # noqa: E501
        :rtype: RiskscoreRiskCategoryType
        """
        return self._risk_category_type

    @risk_category_type.setter
    def risk_category_type(self, risk_category_type):
        """Sets the risk_category_type of this FirewallTestCategorySeverity.


        :param risk_category_type: The risk_category_type of this FirewallTestCategorySeverity.  # noqa: E501
        :type: RiskscoreRiskCategoryType
        """

        self._risk_category_type = risk_category_type

    @property
    def severity(self):
        """Gets the severity of this FirewallTestCategorySeverity.  # noqa: E501


        :return: The severity of this FirewallTestCategorySeverity.  # noqa: E501
        :rtype: RimeSeverity
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this FirewallTestCategorySeverity.


        :param severity: The severity of this FirewallTestCategorySeverity.  # noqa: E501
        :type: RimeSeverity
        """

        self._severity = severity

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FirewallTestCategorySeverity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FirewallTestCategorySeverity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
