# coding: utf-8

"""
    Robust Intelligence REST API

    API methods for Robust Intelligence. Users must authenticate using the `X-Firewall-Auth-Token` for all the firewall methods and `rime-api-key` for all other methods.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: dev@robustintelligence.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RimeContinuousTestRunProgress(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_run': 'RimeTestRunProgress',
        'bin_start_time': 'datetime',
        'bin_end_time': 'datetime'
    }

    attribute_map = {
        'test_run': 'testRun',
        'bin_start_time': 'binStartTime',
        'bin_end_time': 'binEndTime'
    }

    def __init__(self, test_run=None, bin_start_time=None, bin_end_time=None):  # noqa: E501
        """RimeContinuousTestRunProgress - a model defined in Swagger"""  # noqa: E501
        self._test_run = None
        self._bin_start_time = None
        self._bin_end_time = None
        self.discriminator = None
        if test_run is not None:
            self.test_run = test_run
        if bin_start_time is not None:
            self.bin_start_time = bin_start_time
        if bin_end_time is not None:
            self.bin_end_time = bin_end_time

    @property
    def test_run(self):
        """Gets the test_run of this RimeContinuousTestRunProgress.  # noqa: E501


        :return: The test_run of this RimeContinuousTestRunProgress.  # noqa: E501
        :rtype: RimeTestRunProgress
        """
        return self._test_run

    @test_run.setter
    def test_run(self, test_run):
        """Sets the test_run of this RimeContinuousTestRunProgress.


        :param test_run: The test_run of this RimeContinuousTestRunProgress.  # noqa: E501
        :type: RimeTestRunProgress
        """

        self._test_run = test_run

    @property
    def bin_start_time(self):
        """Gets the bin_start_time of this RimeContinuousTestRunProgress.  # noqa: E501


        :return: The bin_start_time of this RimeContinuousTestRunProgress.  # noqa: E501
        :rtype: datetime
        """
        return self._bin_start_time

    @bin_start_time.setter
    def bin_start_time(self, bin_start_time):
        """Sets the bin_start_time of this RimeContinuousTestRunProgress.


        :param bin_start_time: The bin_start_time of this RimeContinuousTestRunProgress.  # noqa: E501
        :type: datetime
        """

        self._bin_start_time = bin_start_time

    @property
    def bin_end_time(self):
        """Gets the bin_end_time of this RimeContinuousTestRunProgress.  # noqa: E501


        :return: The bin_end_time of this RimeContinuousTestRunProgress.  # noqa: E501
        :rtype: datetime
        """
        return self._bin_end_time

    @bin_end_time.setter
    def bin_end_time(self, bin_end_time):
        """Sets the bin_end_time of this RimeContinuousTestRunProgress.


        :param bin_end_time: The bin_end_time of this RimeContinuousTestRunProgress.  # noqa: E501
        :type: datetime
        """

        self._bin_end_time = bin_end_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RimeContinuousTestRunProgress, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RimeContinuousTestRunProgress):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
