from .client import DifyDatasetClient
from .exceptions import (
    ERROR_CODE_MAPPING,
    DifyAPIError,
    DifyAuthenticationError,
    DifyConflictError,
    DifyConnectionError,
    DifyError,
    DifyNotFoundError,
    DifyServerError,
    DifyTimeoutError,
    DifyValidationError,
)
from .models import (
    CreateDatasetRequest,
    CreateDocumentByFileRequest,
    CreateDocumentByTextRequest,
    CreateMetadataRequest,
    CreateSegmentRequest,
    Dataset,
    DataSourceInfo,
    Document,
    DocumentMetadata,
    DocumentMetadataRequest,
    DocumentResponse,
    IndexingStatus,
    IndexingStatusResponse,
    Metadata,
    MetadataListResponse,
    MetadataValue,
    PaginatedResponse,
    PreProcessingRule,
    ProcessRule,
    ProcessRuleConfig,
    Segment,
    Segmentation,
    SegmentResponse,
    SuccessResponse,
    UpdateDocumentByTextRequest,
    UpdateMetadataRequest,
    UpdateSegmentRequest,
)

__version__ = "0.1.0"

__all__ = [
    "DifyDatasetClient",
    # Exceptions
    "DifyError",
    "DifyAPIError",
    "DifyAuthenticationError",
    "DifyValidationError",
    "DifyNotFoundError",
    "DifyConflictError",
    "DifyServerError",
    "DifyConnectionError",
    "DifyTimeoutError",
    "ERROR_CODE_MAPPING",
    # Models
    "DataSourceInfo",
    "ProcessRule",
    "PreProcessingRule",
    "Segmentation",
    "ProcessRuleConfig",
    "Document",
    "Dataset",
    "Segment",
    "IndexingStatus",
    "Metadata",
    "MetadataValue",
    "DocumentMetadata",
    "PaginatedResponse",
    "CreateDocumentByTextRequest",
    "CreateDocumentByFileRequest",
    "CreateDatasetRequest",
    "UpdateDocumentByTextRequest",
    "CreateSegmentRequest",
    "UpdateSegmentRequest",
    "CreateMetadataRequest",
    "UpdateMetadataRequest",
    "DocumentMetadataRequest",
    "DocumentResponse",
    "SegmentResponse",
    "MetadataListResponse",
    "IndexingStatusResponse",
    "SuccessResponse",
]
