def not_specific_poi_website_list():
        returned = []
        for root in [
            "lewiatan.pl",
            "zahirkebab.pl",
            "mcdonalds.pl", "mcdonalds.pl/restauracje",
            "rossmann.pl",
            "empik.com",
            "orange.pl", "salony.orange.pl", "orange.pl/start.phtml",
            "biedronka.pl/pl", "biedronka.pl", "biedronka.pl/sklepy",
            "spar.pl",
            "polomarket.pl",
            "lotos.pl",
            "agatameble.pl",
            "sklepy-odido.pl",
            "carters.com",
            "cariboucoffee.com",
            "californiaclosets.com",
            "aviapolska.pl",
            "baskinrobbins.com",
            "7eleven.com", '7-eleven.com',
            "truevalue.com",
            "aviastacjapaliw.pl",
            "hypovereinsbank.de",
            "arbys.com",
            "inpost.pl",
            "itaka.pl",
            'att.com',
            "aldi-sued.de",
            'dickeys.com',
            'dairyqueen.com',
            'jmclaughlin.com',
            'jiffylube.com',
            'publicstorage.com',
            'saladandgo.com',
            'circlek.pl',
            'huddlehouse.com',
            'decathlon.pl',
            'dagrasso.pl',
            'hebe.pl',
            'penny.de',
            'ameripriseadvisors.com',
            'familydollar.com',
            'shopfamilyfare.com',
            'festfoods.com',
            'sleepnumber.com',
            'sunloan.com',
            'thefreshgrocer.com',
            'goldsmiths.co.uk',
            'leroymerlin.pl',
            'delikatesy.pl',
            'topaz24.pl',
            'dominos.de',
            'stokrotka.pl',
            'buffalowildwings.com',
            'locator.chase.com',
            'commercialtire.com',
            'crumblcookies.com',
            'turkeyhillcstores.com',
            'cumberlandfarms.com',
            'loafnjug.com',
            'kwikshop.com',
            'goodyearautoservice.com',
            'roddapaint.com',
            'verizon.com',
            'supersigma.com',
            'stroilioro.com',
            'cukierniasowa.pl',
            'sklepy.mediaexpert.pl',
            'putka.pl',
            'biomarkt.de',
            'lecrobag.de',
            'kamps.de',
            'anntaylor.com',
            'brw.pl',
            'berlindonerkebap.com',
            'concentra.com',
            'ilovedirtcheap.com',
            'cousinssubs.com',
            'papersource.com',
            "empik.pl",
            'mercator.si',
            'cvs.com',
            'bucadibeppo.com',
            'bobevans.com',
            'toom.de',
            'tegut.com',
            'tedox.de',
            'rossmann.de',
            'rewe.de',
            'jewson.co.uk',
            'greggs.co.uk',
            'anacondastores.com',
            'mitre10.com.au',
            'decathlon.it',
            'decathlon.de',
            'buffaloexchange.com',
            'locations.checkers.com',
            'brookdale.com',
            'belletire.com',
            'dunhamssports.com',
            'laseraway.com',
            'krispykrunchy.com',
            'naturalgrocers.com',
            'bubbas33.com',
            'bricksandminifigs.com',
            'bevmo.com',
            'superbiomarkt.de',
            'shops.vodafone.de',
            'turkeyhillstores.com',
            'fiveguys.de',
            'restaurants.fiveguys.de',
            'fiveguys.com',
            'restaurants.fiveguys.com',
            'locations.pizzahut.com',
            'locations.quiktrip.com',
            'wafflehouse.com',
            'brw.com.pl',
            'mebloexpert.eu',
            'vertretung.allianz.de',
            'oxfam.org.uk',
            'gap.uk.com',
            'vinnies.org.au',
            'store.nandos.co.za',
            'stores.truevalue.com',
            'truevalue.com',
            'cap-markt.de',
            'commercialtire.com',
            'waxcenter.com',
            'pigglywigglybirmingham.com',
            'animates.co.nz',
            'mcdonalds.com.au',
            'salvosstores.com.au',
            'denns-biomarkt.de',
            'edeka-meyer.com',
            'bestbuy.ca',
            'sobeys.ca',
            'zambrero.com',
            'zambrero.com.au',
            'subway.pl',
        ]:
            # handles also broken such as
            # website = ps://www.biedronka.pl
            for protocol in ["", "http://", "https://", "ps://"]:
                for www in ["", "www."]:
                    for common_subdomains in ["", "m.", "locations."]:
                        for suffix in ["", "/"]:
                            returned.append(protocol + www + common_subdomains + root + suffix)
        returned += [
            'https://www.circlek.pl/wyszukaj-stacje',
            'http://www.statoil.pl',
            'Biedronka.PL',
            'https://www.aldi-sued.de/de/homepage.html',  # seems to be added by some ATP?
            'https://allegro.pl/kampania/one/znajdz-nas',
            'https://allegro.pl/kampania/one',
            'https://www.castorama.pl',
            'https://www.biedronka.pl',
            'http://www.sowa-cukiernia.com.pl',
            'https://www.berlindonerkebap.com',
            'http://zahirkebab.pl',
            'https://twoj.inpost.pl/pl/znajdz-punkt-inpost',
            'https://inpost.pl/pl/znajdz-punkt-inpost',
            'https://www.berlindonerkebap.pl',
            'https://berlindonerkebab.pl',
            'https://www.telekom.de/start',
            'www.bestbuy.ca/en-CA/home.aspx',
            'https://www.dairyqueen.com/ca-en/',
        ]
        return returned
