"""Translation mappings for API parameters from English to Chinese."""

translate: dict[str, str] = {
    "article_number": "法條編號",
    "bill_flow_status": "議案流程.狀態",
    "bill_no": "議案編號",
    "bill_no_nested": "議事網資料.關係文書.議案.議案編號",
    "bill_number": "議案編號",
    "bill_status": "議案狀態",
    "bill_type": "議案類別",
    "co_proposer": "連署人",
    "committee_code": "委員會代號",
    "committee_code_detailed": "會議資料.委員會代碼",
    "committee_type": "委員會類別",
    "comt_cd": "委員會代號",
    "date": "日期",
    "ivod_id": "IVOD_ID",
    "law_number": "法律編號",
    "law_number_nested": "議事網資料.關係文書.議案.法律編號",
    "limit": "限制筆數",
    "meet_id": "會議資料.會議編號",
    "meeting_code": "會議代碼",
    "meeting_code_data": "會議資料.會議代碼",
    "meeting_code_detailed": "會議.會議代碼",
    "meeting_type": "會議種類",
    "member": "會議資料.出席委員",
    "member_name": "委員名稱",
    "output_fields": "輸出欄位",
    "page": "頁數",
    "proposal_date": "提案日期",
    "proposal_number": "提案編號",
    "proposal_source": "提案來源",
    "proposer": "提案人",
    "reference_number": "字號",
    "session": "會期",
    "term": "屆",
    "gazette_id": "公報編號",
    "gazette_agenda_id": "公報議程編號",
    "meeting_date": "會議日期",
    "volume": "卷",
    "interpellation_member": "質詢委員",
    "interpellation_id": "質詢編號",
    "video_type": "影片種類",
    # Laws API translations
    "law_id": "法律編號",
    "law_category": "類別",
    "parent_law_number": "母法編號",
    "law_status": "法律狀態",
    "authority": "主管機關",
    "latest_version_date": "最新版本.日期",
    # Legislators API translations
    "party": "黨籍",
    "district_name": "選區名稱",
    "legislator_id": "歷屆立法委員編號",
    "legislator_name": "委員姓名",
    "version_number": "版本編號",
    "action": "動作",
    "main_proposer": "歷程.主提案",
    "progress": "歷程.進度",
    "current_version": "現行版本",
    # Law contents API translations
    "law_content_id": "法條編號",
    "version_id": "版本編號",
    "order": "順序",
    "law_article_number": "條號",
    "current_version_status": "現行版",
    "version_tracking": "版本追蹤",
    # Meets API translations
    "meeting_attendee": "會議資料.出席委員",
    "meeting_id": "會議資料.會議編號",
    "meeting_bills_bill_no": "議事網資料.關係文書.議案.議案編號",
    "meeting_bills_law_no": "議事網資料.關係文書.議案.法律編號",
}
