# -*- coding: utf-8 -*-

class Cipher1Enum(object):

    """Implementation of the 'Cipher1' enum.

    TODO: type enum description here.

    Attributes:
        TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384: TODO: type description here.
        TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256: TODO: type description here.
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384: TODO: type description here.
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256: TODO: type description here.
        TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA: TODO: type description here.
        TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA: TODO: type description here.
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA: TODO: type description here.
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA: TODO: type description here.
        TLS_RSA_WITH_AES_256_GCM_SHA384: TODO: type description here.
        TLS_RSA_WITH_AES_128_GCM_SHA256: TODO: type description here.
        TLS_RSA_WITH_AES_256_CBC_SHA: TODO: type description here.
        TLS_RSA_WITH_AES_128_CBC_SHA: TODO: type description here.

    """

    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384'

    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256'

    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'

    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256'

    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 'TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA'

    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 'TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA'

    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA'

    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA'

    TLS_RSA_WITH_AES_256_GCM_SHA384 = 'TLS_RSA_WITH_AES_256_GCM_SHA384'

    TLS_RSA_WITH_AES_128_GCM_SHA256 = 'TLS_RSA_WITH_AES_128_GCM_SHA256'

    TLS_RSA_WITH_AES_256_CBC_SHA = 'TLS_RSA_WITH_AES_256_CBC_SHA'

    TLS_RSA_WITH_AES_128_CBC_SHA = 'TLS_RSA_WITH_AES_128_CBC_SHA'

