from .LOG import LOG
from .PARALLEL_PROCESS_TESTS_A import PARALLEL_PROCESS_TESTS_A
from .PARALLEL_PROCESS_TESTS_B import PARALLEL_PROCESS_TESTS_B
from PARALLEL_PROCESS_TESTS_C1 import PARALLEL_PROCESS_TESTS_C1
from PARALLEL_PROCESS_TESTS_C2 import PARALLEL_PROCESS_TESTS_C2
from PARALLEL_PROCESS_TESTS_C3 import PARALLEL_PROCESS_TESTS_C3
from .PARALLEL_PROCESS_TESTS_D import PARALLEL_PROCESS_TESTS_D
from .PARALLEL_PROCESS_TESTS_E import PARALLEL_PROCESS_TESTS_E
from .PARALLEL_PROCESS_TESTS_F import PARALLEL_PROCESS_TESTS_F
from .PARALLEL_PROCESS_TESTS_G import PARALLEL_PROCESS_TESTS_G
from .PARALLEL_PROCESS_TESTS_H import PARALLEL_PROCESS_TESTS_H
from .PARALLEL_PROCESS_TESTS_I import PARALLEL_PROCESS_TESTS_I
from .PARALLEL_PROCESS_TESTS_J import PARALLEL_PROCESS_TESTS_J
from .PARALLEL_PROCESS_TESTS_L import PARALLEL_PROCESS_TESTS_L
from .PARALLEL_PROCESS_TESTS_M import PARALLEL_PROCESS_TESTS_M
from .PARALLEL_PROCESS_WRAPPER_TEST import PARALLEL_PROCESS_WRAPPER_TEST


class PARALLEL_PROCESS_TESTS:

    @classmethod
    def TestAll(cls):
        '''👉️ Test the parallel process.'''
        
        PARALLEL_PROCESS_WRAPPER_TEST.TestAll()

        PARALLEL_PROCESS_TESTS_A.TestAll()
        PARALLEL_PROCESS_TESTS_B.TestAll()
        PARALLEL_PROCESS_TESTS_C1.TestAll()
        PARALLEL_PROCESS_TESTS_C2.TestAll()
        PARALLEL_PROCESS_TESTS_C3.TestAll()
        PARALLEL_PROCESS_TESTS_D.TestAll()
        PARALLEL_PROCESS_TESTS_E.TestAll()
        PARALLEL_PROCESS_TESTS_F.TestAll()
        PARALLEL_PROCESS_TESTS_G.TestAll()
        PARALLEL_PROCESS_TESTS_H.TestAll()
        PARALLEL_PROCESS_TESTS_I.TestAll()
        PARALLEL_PROCESS_TESTS_J.TestAll()
        PARALLEL_PROCESS_TESTS_L.TestAll()
        PARALLEL_PROCESS_TESTS_M.TestAll()

        LOG.PARALLEL().SetClassDone()