# Generated by Django 4.2.19 on 2025-04-01 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incursions', '0013_alter_activefleet_options_alter_activefleet_fleet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activefleet',
            name='fleet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='incursions.fleet', verbose_name='Fleet'),
            preserve_default=False,
        ),
    ]
