# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim

# Install dependencies for building
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*

# Set work directory
WORKDIR /app

# Copy project files including README for packaging
COPY pyproject.toml uv.lock server.py README.md .

# Install the MCP server package
RUN pip install --no-cache-dir .

# Default command to run the MCP server over stdio
CMD ["python", "server.py"]
