from .LOG import LOG
from PARALLEL_THREAD_TESTS_1 import PARALLEL_THREAD_TESTS_1
from PARALLEL_THREAD_TESTS_2 import PARALLEL_THREAD_TESTS_2
from .PARALLEL_THREAD_TESTS_A import PARALLEL_THREAD_TESTS_A
from .PARALLEL_THREAD_TESTS_B import PARALLEL_THREAD_TESTS_B
from .PARALLEL_THREAD_TESTS_C import PARALLEL_THREAD_TESTS_C
from .PARALLEL_THREAD_TESTS_D import PARALLEL_THREAD_TESTS_D
from .PARALLEL_THREAD_TESTS_E import PARALLEL_THREAD_TESTS_E
from .PARALLEL_THREAD_TESTS_F import PARALLEL_THREAD_TESTS_F
from .PARALLEL_THREAD_TESTS_G import PARALLEL_THREAD_TESTS_G

class PARALLEL_THREAD_TESTS:

    ICON = '🧪'


    @classmethod
    def TestThreads(cls):
        LOG.Print('🧪‍ PARALLEL_THREAD_TESTS.TestParallelRunner()')
        
        PARALLEL_THREAD_TESTS_1.TestAll()
        PARALLEL_THREAD_TESTS_2.TestAll()
        PARALLEL_THREAD_TESTS_A.TestAll()
        PARALLEL_THREAD_TESTS_B.TestAll()
        PARALLEL_THREAD_TESTS_C.TestAll()
        PARALLEL_THREAD_TESTS_D.TestAll()
        PARALLEL_THREAD_TESTS_E.TestAll()
        PARALLEL_THREAD_TESTS_F.TestAll()
        PARALLEL_THREAD_TESTS_G.TestAll()

        LOG.PARALLEL().SetClassDone()

        