# Generated by Django 5.2.5 on 2025-08-07 12:42

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_organization_to_site(apps, schema_editor):
    """
    Migrate from organization-based to site-based schema.
    This handles upgrades from v1.x to v2.x.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if old organization table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='sb_sync_user_organization'
        """)
        has_old_table = cursor.fetchone() is not None
        
        if has_old_table:
            # Create default site if none exists
            cursor.execute("""
                INSERT OR IGNORE INTO django_site (id, name, domain)
                VALUES (1, 'Default Organization', 'example.com')
            """)
            
            # Copy data from old table to new table
            cursor.execute("""
                INSERT INTO sb_sync_user_site (user_id, site_id, group_id, is_active, created_at, updated_at)
                SELECT user_id, organization_id, group_id, is_active, created_at, updated_at
                FROM sb_sync_user_organization
            """)
            
            # Drop old table
            cursor.execute("DROP TABLE IF EXISTS sb_sync_user_organization")


def reverse_migrate_organization_to_site(apps, schema_editor):
    """
    Reverse migration (if needed for rollback).
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if new site table exists
        cursor.execute("""
            SELECT name FROM sqlite_master 
            WHERE type='table' AND name='sb_sync_user_site'
        """)
        has_new_table = cursor.fetchone() is not None
        
        if has_new_table:
            # Create old table structure
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS sb_sync_user_organization (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    organization_id INTEGER NOT NULL,
                    group_id INTEGER,
                    is_active BOOLEAN NOT NULL DEFAULT 1,
                    created_at DATETIME NOT NULL,
                    updated_at DATETIME NOT NULL,
                    FOREIGN KEY (user_id) REFERENCES auth_user (id),
                    FOREIGN KEY (organization_id) REFERENCES django_site (id),
                    FOREIGN KEY (group_id) REFERENCES auth_group (id)
                )
            """)
            
            # Copy data back
            cursor.execute("""
                INSERT INTO sb_sync_user_organization (user_id, organization_id, group_id, is_active, created_at, updated_at)
                SELECT user_id, site_id, group_id, is_active, created_at, updated_at
                FROM sb_sync_user_site
            """)
            
            # Drop new table
            cursor.execute("DROP TABLE IF EXISTS sb_sync_user_site")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run organization to site migration first
        migrations.RunPython(
            migrate_organization_to_site,
            reverse_migrate_organization_to_site,
        ),
        
        # Then create all the new models
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Configuration',
                'verbose_name_plural': 'Sync Configurations',
                'db_table': 'sb_sync_configuration',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDataFilter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('filter_name', models.CharField(db_index=True, max_length=255)),
                ('filter_condition', models.TextField(help_text='JSON filter condition')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='Django Site representing the site', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical Data Filter',
                'verbose_name_plural': 'historical Data Filters',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalModelPermission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('can_push', models.BooleanField(db_index=True, default=False)),
                ('can_pull', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='Django Site representing the site', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical Model Permission',
                'verbose_name_plural': 'historical Model Permissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserSite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='Django Site representing the site', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical User Site',
                'verbose_name_plural': 'historical User Sites',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserSyncMetadata',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='Django Site representing the site', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site')),
            ],
            options={
                'verbose_name': 'historical User Sync Metadata',
                'verbose_name_plural': 'historical User Sync Metadatas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('records_processed', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance Metrics',
                'verbose_name_plural': 'Performance Metrics',
                'db_table': 'sb_sync_performance_metrics',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerformanceMetrics',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('records_processed', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Performance Metrics',
                'verbose_name_plural': 'historical Performance Metricss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sb_sync_log',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSyncLog',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('operation', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, editable=False, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sync Log',
                'verbose_name_plural': 'historical Sync Logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Metadata',
                'verbose_name_plural': 'Sync Metadatas',
                'db_table': 'sb_sync_metadata',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSyncMetadata',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Sync Metadata',
                'verbose_name_plural': 'historical Sync Metadatas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('site', models.ForeignKey(help_text='Django Site representing the site', on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Site',
                'verbose_name_plural': 'User Sites',
                'db_table': 'sb_sync_user_site',
            },
        ),
        migrations.CreateModel(
            name='UserSyncMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('total_synced', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(help_text='Django Site representing the site', on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Sync Metadata',
                'verbose_name_plural': 'User Sync Metadatas',
                'db_table': 'sb_sync_user_sync_metadata',
            },
        ),
        migrations.CreateModel(
            name='DataFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('filter_name', models.CharField(db_index=True, max_length=255)),
                ('filter_condition', models.TextField(help_text='JSON filter condition')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('site', models.ForeignKey(help_text='Django Site representing the site', on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Data Filter',
                'verbose_name_plural': 'Data Filters',
                'db_table': 'sb_sync_data_filter',
            },
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=255)),
                ('can_push', models.BooleanField(db_index=True, default=False)),
                ('can_pull', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('site', models.ForeignKey(help_text='Django Site representing the site', on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Model Permission',
                'verbose_name_plural': 'Model Permissions',
                'db_table': 'sb_sync_model_permission',
            },
        ),
        # Create indexes for better performance
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['timestamp', 'operation'], name='sb_sync_log_timesta_11c11b_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['user', 'operation'], name='sb_sync_log_user_id_26fea0_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status', 'timestamp'], name='sb_sync_log_status_2999e8_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['model_name', 'timestamp'], name='sb_sync_log_model_n_efb3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['user', 'status', 'timestamp'], name='sb_sync_log_user_id_e4ca58_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['operation', 'status', 'timestamp'], name='sb_sync_log_operati_c09add_idx'),
        ),
        migrations.AddIndex(
            model_name='usersite',
            index=models.Index(fields=['user', 'site'], name='sb_sync_use_user_id_86f418_idx'),
        ),
        migrations.AddIndex(
            model_name='usersite',
            index=models.Index(fields=['site', 'group'], name='sb_sync_use_site_id_d19a94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersite',
            unique_together={('user', 'site')},
        ),
        migrations.AddIndex(
            model_name='usersyncmetadata',
            index=models.Index(fields=['user', 'site', 'model_name'], name='sb_sync_use_user_id_076a18_idx'),
        ),
        migrations.AddIndex(
            model_name='usersyncmetadata',
            index=models.Index(fields=['site', 'model_name', 'last_sync'], name='sb_sync_use_site_id_8027d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usersyncmetadata',
            unique_together={('user', 'site', 'model_name')},
        ),
    ]
