
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: alpacloud/crdvis:alpacloud.crdvis

from setuptools import setup

setup(**{
    'author': 'Daniel Goldman',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
        'Topic :: Utilities',
        'Topic :: System :: Systems Administration',
    ],
    'description': 'A visualiser for Kubernetes CRDs',
    'entry_points': {
        'console_scripts': [
            'crdvis = alpacloud.crdvis:run_crdvis',
        ],
    },
    'install_requires': (
        'PyYAML>=6.0',
        'mypy~=1.16.1',
        'pydantic~=2.11.7',
        'requests~=2.32',
        'rich~=14.1',
        'textual~=5.2.0',
        'types-PyYAML',
        'types-requests',
    ),
    'license': 'Round Robin 2.0.0',
    'long_description': """# CRD Visualiser

Visualise a CRD! CRDs are giant, and it's too hard to find the information you need in them. When you're searching for the name of a field, you have to jump past results from other fields' descriptions. When you want to see what attributes are valid at a particular level, you have to scroll past the whole tree. Even once you find what you're looking for, you have to parse OpenAPI in your head. Just don't! Let machines help.

`crdvis` presents CRDs in a concise view. The tree browser shows a CRD the way you'd want it. The `goto` function searches field names only, and the `find` function searches descriptions too. Simple field types are inlined.

![CRD Visualiser Interface](crdvis.png)

## Loading a CRD

`crdvis` can load CRDs from several locations:
- your filesystem : give it a valid path or something prefixed with `file://`
- the web : urls for `http://` and `https://` will be loaded. GitHub urls will automatically request the raw file, so you don't have to click through to the "raw" version
- an active Kubernetes cluster : `kubectl://` will use kubectl to pull a CRD from your current Kubernetes cluster
- raw CRD : copypaste it in
""",
    'long_description_content_type': 'text/markdown',
    'name': 'alpacloud.crdvis',
    'namespace_packages': (
    ),
    'package_data': {
    },
    'packages': (
        'alpacloud',
        'alpacloud.crdvis',
    ),
    'python_requires': '>=3.11',
    'version': '0.1.0',
})
