from enum import Enum
from proalgotrader_core.protocols.enums.market_type import MarketType as MarketType
from proalgotrader_core.protocols.enums.product_type import ProductType as ProductType

class AccountType(Enum):
    CASH_INTRADAY = ...
    CASH_POSITIONAL = ...
    DERIVATIVE_INTRADAY = ...
    DERIVATIVE_POSITIONAL = ...
